export const types = {
  ADD_TO_CART: 'ADD_TO_CART',

  FILL_CART: 'FILL_CART',
  FILL_CART_TOTAL_PRICE: 'FILL_CART_TOTAL_PRICE',

  CLEAR_CART: 'CLEAR_CART',
  CART_TOTAL: 'CART_TOTAL',

  BOOKS_READY_FOR_PURCHASE: 'BOOKS_READY_FOR_PURCHASE',

  PURCHASE_ASYNC: 'PURCHASE_ASYNC',
  PURCHASE_ASYNC_SUCCESS: 'PURCHASE_ASYNC_SUCCESS',
  PURCHASE_ASYNC_FAILURE: 'PURCHASE_ASYNC_FAILURE',
};
