export const types = {
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',

  TOTAL_PRICE: 'TOTAL_PRICE',
  UPDATE_TOTAL_PRICE: 'UPDATE_TOTAL_PRICE',
  UPDATE_TOTAL_PRICE_ON_BLUR: 'UPDATE_TOTAL_PRICE_ON_BLUR',
  SET_BOOK_PRICE_ON_FOCUS: 'SET_BOOK_PRICE_ON_FOCUS',

  BOOKS_AVAILABILITY: 'BOOKS_AVAILABILITY',

  SET_COUNT: 'SET_COUNT',
  IS_INPUT_VALID: 'IS_INPUT_VALID',
};
