export const types = {
  SIGN_IN_ASYNC: 'SIGN_IN_ASYNC',
  SIGN_IN_ASYNC_SUCCESS: 'SIGN_IN_ASYNC_SUCCESS',
  SIGN_IN_ASYNC_ERROR: 'SIGN_IN_ASYNC_ERROR',

  AUTHENTICATE: 'AUTHENTICATE',
  SIGN_OUT: 'SIGN_OUT',
};
