export const types = {
  SIGN_IN_ASYNC: 'SIGN_IN_ASYNC',
  SIGN_IN_ASYNC_SUCCESS: 'SIGN_IN_ASYNC_SUCCESS',
  SIGN_IN_ASYNC_ERROR: 'SIGN_IN_ASYNC_ERROR',

  START_FETCHING: 'START_FETCHING',
  STOP_FETCHING: 'STOP_FETCHING',

};
