export const types = {
  FETCH_BOOK_ASYNC: 'FETCH_BOOK_ASYNC',
  FETCH_BOOK_ASYNC_SUCCESS: 'FETCH_BOOK_ASYNC_SUCCESS',
  FETCH_BOOK_ASYNC_ERROR: 'FETCH_BOOK_ASYNC_ERROR',

  CLEAR_BOOK: 'CLEAR_BOOK',
  VIEW_BOOK: 'VIEW_BOOK',
  RESET_ERROR: 'RESET_ERROR',
};
